logging:
  level:
    root: info
    com.sens: debug

server:
  port: 8081

spring:
  security:
    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: web-front
#            authorization-grant-type: authorization_code
#            scope:
#              - openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/czetsuyatech
#            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/czetsuyatech
