logging:
  level:
    root: info
    com.czetsuyatech: debug

server:
  port: 8081

app:
  base-url: http://localhost:8081

keycloak:
  base-url: http://localhost:8080
  realm: czetsuyatech


spring:
  codec:
    max-in-memory-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:33069}/${DB_SCHEMA:ct_db}?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:db_user}
    password: ${DB_PASSWORD:db_pass_123}
    hikari:
      connection-test-query: SELECT 1
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 17
      minimum-idle: 10
      pool-name: ct-pool
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 5
          time_zone: UTC
        generate_statistics: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: web-front
            client-secret: ${KEYCLOAK_CLIENT_SECRET:1dF4vDiOed5ff4fRepYrlqxBKPQYmujP}
            authorization-grant-type: authorization_code
            redirect-uri: ${app.base-url}/login/oauth2/code/keycloak
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: ${keycloak.base-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.base-url}/realms/${keycloak.realm}
  mvc:
    converters:
      preferred-json-mapper: gson
  gson:
    enable-complex-map-key-serialization: on
