version: '3.3'

services:
  keycloak:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: keycloak.admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak.admin
      KC_FEATURES: token-exchange,admin-fine-grained-authz
